/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leonuxdolares;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Amal-AM0105
 */
public class form extends javax.swing.JFrame {
    String _driver = "com.mysql.jdbc.Driver";
    Connection _conn = null;
    
    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        jValorDivisa.setText("");
        jValorDivisa.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if (ch < '0' || ch > '9'){
                    e.consume();
                }
            }
            @Override
            public void keyPressed(KeyEvent e) {                
            }

            @Override
            public void keyReleased(KeyEvent e) {                
            }            
        });
        
        String host = "10.10.0.199:3306";
        String name = "00000001";
        String usuario = "root";
        String clave = "123";
        
        try {
            Class.forName(_driver).newInstance();
            _conn = DriverManager.getConnection("jdbc:mysql://"+ host +"/"+name, usuario, clave);           
        } catch(Exception e){
            e.printStackTrace();
        }
        
        
        try {
            Statement st = _conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT usuario FROM sistema_configuracion WHERE codigo = 'GLOBAL12'");

            if (rs.next()){
                jValorDivisa.setText(rs.getString(1));
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al consultar tasa en base de datos"); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jValorDivisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leonux");
        setLocation(new java.awt.Point(300, 280));
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Herramienta para calcular precio en base a divisa");

        jLabel2.setText("Valor Divisa:");

        jValorDivisa.setText("Valor divisa");
        jValorDivisa.setMinimumSize(new java.awt.Dimension(6, 30));
        jValorDivisa.setPreferredSize(new java.awt.Dimension(100, 30));
        jValorDivisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorDivisaActionPerformed(evt);
            }
        });

        jButton1.setLabel("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jValorDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jValorDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValorDivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorDivisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorDivisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            BigDecimal divisa = new BigDecimal(jValorDivisa.getText());
            
            String sqlquery = "UPDATE sistema_configuracion SET usuario = '"+divisa+"'"
                    + " WHERE codigo = 'GLOBAL12'";
            Statement st = _conn.createStatement();            
            int i1 = st.executeUpdate(sqlquery);
            
            sqlquery = "SELECT auto, referencia, tasa FROM productos WHERE referencia <> ''";
            ResultSet rs2 = st.executeQuery(sqlquery);
            int cant = 0;
            while(rs2.next()){
                String auto = rs2.getString(1);
                BigDecimal referencia = new BigDecimal(rs2.getString(2));
                float f = 1;
                if(rs2.getFloat(3)!=0){
                    f = 1+(rs2.getFloat(3)/100);
                }                
                BigDecimal factor = new BigDecimal(f);
                BigDecimal precioFull = referencia.multiply(divisa);                
                BigDecimal precioNeto = precioFull.divide(factor, 2, RoundingMode.HALF_UP);
                
                //System.out.printf("%s %s", precioFull.toString(), precioNeto.toString());
                
                sqlquery = "UPDATE productos SET precio_1 = '"+precioNeto.toString()+"' WHERE auto = '"+auto+"'";
                Statement st2 = _conn.createStatement();
                int i2 = st2.executeUpdate(sqlquery);
                cant++;
            }                        
            
            JOptionPane.showMessageDialog(this, "Proceso completado\n"+cant+" Productos actualizados"); 
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error"); 
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }
    
    public void cambiar(){
        ResultSet rs;
        Statement st;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jValorDivisa;
    // End of variables declaration//GEN-END:variables
}
